### ISSUE TITLE
Mobile view not seeing rest of todo...

### ISSUE THREAD

**Issue by Beast141** [cozy/todos#43]
The problem is when i am on my mobile browser firefox on android, i can navigate and see everything in mobile view as it is. But when i enter a todo on a line and it is a long sentence, after writing it and saving it, i cannot view the rest of the sentence unless i put the curser in there and i move it towards the end of the sentence to read what i wrote.

an example sentence: Today i need to phone the plumber because i need to ask him a few things."

and after i have saved it.. in the mobile firefox broswer i would see it like this:

"Today i need to phone the plumber because i need to..."

Please can anyone fix this? is this a bug?

thanks

**Comment by Beast141** [comment]
Sorry nevermind - realized i can hold down the todo and move it towards the left side of the screen so that i may view the rest. Please delete this issue i opened.

**Comment by frankrousseau** [comment]
Cool :)
